name: tashil_food_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1 

environment:
  # sdk: '>=2.19.0-255.2.beta <3.0.0'
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cached_network_image: ^3.2.3
  clip_shadow: ^0.2.1
  cloud_firestore: ^4.3.0
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6
  lottie: ^2.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  persistent_bottom_nav_bar: ^5.0.2
  pin_code_fields: ^7.4.0
  readmore: ^2.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_native_splash:
  image: assets/images/splash/splash.png
  color: "ffffff"
  android_disable_fullscreen: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 300
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 400
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
